import SwiftUI

extension Image {
  static let arrowLeftIcon = Image("ArrowLeftIcon")
  static let arrowRightIcon = Image("ArrowRightIcon")
  static let aiCoachIcon = Image("AIcoachIcon")
  static let aiCoachIconActive = Image("AIcoachIconActive")
  static let caretDownIcon = Image("CaretDownpIcon")
  static let caretUpIcon = Image("CaretUpIcon")
  static let chevronDownOutlineIcon = Image("ChevronDownOutlineIcon")
  static let chevronLeftOutlineIcon = Image("ChevronLeftOutlineIcon")
  static let chevronRightOutlineIcon = Image("ChevronRightOutlineIcon")
  static let chevronUpOutlineIcon = Image("ChevronUpOutlineIcon")
  static let homeIcon = Image("HomeIcon")
  static let homeIconActive = Image("HomeIconActive")
  static let infoFilledIcon = Image("InfoFilledIcon")
  static let infoOutlinedIcon = Image("InfoFOutlinedIcon")
  static let menuRoundedIcon = Image("MenuRoundedIcon")
  static let menuIcon = Image("MenuIcon")
  static let menuIconActive = Image("MenuIconActive")
  static let meterialIcon = Image("MeterialIcon")
  static let meterialIconActive = Image("MeterialIconActive")
  static let plusIcon = Image("PlusIcon")
  static let radioIcon = Image("Radio")
  static let searchIcon = Image("SearchIcon")
  static let slotIcon = Image("SlotIcon")
}
