import SwiftUI

enum AppColor {
  static let primaryBlue100 = Color("Primary-blue-100")
  static let primaryBlue200 = Color("Primary-blue-200")
  static let primaryBlue300 = Color("Primary-blue-300")
  static let primaryBlue400 = Color("Primary-blue-400")
  static let primaryBlue500 = Color("Primary-blue-500")
  static let primaryBlue600 = Color("Primary-blue-600")
  static let primaryBlue700 = Color("Primary-blue-700")
  static let primaryBlue800 = Color("Primary-blue-800")
  static let primaryBlue900 = Color("Primary-blue-900")
  static let grayscale100 = Color("Grayscale-100")
  static let grayscale200 = Color("Grayscale-200")
  static let grayscale300 = Color("Grayscale-300")
  static let grayscale400 = Color("Grayscale-400")
  static let grayscale500 = Color("Grayscale-500")
  static let grayscale600 = Color("Grayscale-600")
  static let grayscale700 = Color("Grayscale-700")
  static let grayscale800 = Color("Grayscale-800")
  static let grayscale900 = Color("Grayscale-900")
  static let semanticSafeText = Color("SemanticSafeText")
  static let semanticSafe = Color("SemanticSafe")
  static let semanticWarningText = Color("SemanticWarningText")
  static let semanticWarning = Color("SemanticWarning")
  static let semanticCautionText = Color("SemanticCautionText")
  static let semanticCaution = Color("SemanticCaution")
  static let primaryBlue700Alt = Color("PrimaryBlue700")
}
